# Generated by Django 6.0.3 on 2026-03-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruined_image', models.ImageField(blank=True, null=True, upload_to='artifacts/ruined/')),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='artifacts/reference/')),
                ('ruined_percentage', models.FloatField(blank=True, null=True)),
                ('repair_instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='INITIALIZING', max_length=50)),
                ('repaired_image', models.ImageField(blank=True, null=True, upload_to='artifacts/repaired/')),
                ('validation_score', models.FloatField(blank=True, null=True)),
                ('blueprint_image', models.ImageField(blank=True, null=True, upload_to='artifacts/blueprints/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
