# Generated by Django 5.2.12 on 2026-03-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifacttask',
            name='mesh_glb',
            field=models.FileField(blank=True, null=True, upload_to='artifacts/3d/'),
        ),
        migrations.AddField(
            model_name='artifacttask',
            name='mesh_obj',
            field=models.FileField(blank=True, null=True, upload_to='artifacts/3d/'),
        ),
    ]
